import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

//components
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";
import Features from "@/components/Features";
import About from "@/components/About";
const inter = Inter({ subsets: ["latin"] });
import { useDispatch } from "react-redux";
import { fetchProducts } from "@/redux/features/poductsSlice";
import { useEffect } from "react";
export default function Home() {
  return (
    <>
      <Head>
        <title>Shemsu - Buy & Sell Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className="bg-[#171717] text-light-color">
        <Navbar />
        <Banner />
        <Features />
        <About />
      </div>
    </>
  );
}
